Add Supports to System Message to Language Model
AllYourBot/hostedgpt pull request #542
Opened 2024-11-11 13:24 UTC by papayalabs

2024-11-13 00:32 UTC, krschacht requested changes
This looks good! Just a test, one comment, and also you forgot to commit the schema file. 

Oh, and update again from main.

2024-11-13 00:32 UTC, krschacht commented on app/models/language_model.rb
> +  end
You can cut this, the method is automatically added to all booleans

2024-11-13 17:16 UTC, krschacht approved these changes
Looks great! I made two minor copy changes. As soon as the tests pass, I'll merge this in. Thanks for tackling this one!

2024-11-13 17:27 UTC, krschacht commented
@papayalabs can you look at this one failing test? I don't see an obvious problem with the code or the test

2024-11-13 18:49 UTC, papayalabs commented
@krschacht Hey!

I wrote this 2 tests on RegisterableTest:

`  test "it creates some language models with supports_system_message enabled and some without" do
    people(:ali_invited).update!(personable_type: "User", personable_attributes: { first_name: "John", last_name: "Doe", })
    assert people(:ali_invited).user.language_models.where(supports_system_message: false).present?
    assert people(:ali_invited).user.language_models.where(supports_system_message: true).present?
  end

  test "make sure gpt-best(first language model) has supports_system_message: true" do
    people(:ali_invited).update!(personable_type: "User", personable_attributes: { first_name: "John", last_name: "Doe", })
    assert_equal people(:ali_invited).user.language_models.first.supports_system_message, true
  end`

And supports_system_message is true but when reach the test (edit should have supports_system_message checkbox checked) comes as false.

2024-11-13 19:14 UTC, papayalabs commented
Hey @krschacht! Now all tests pass.

2024-11-16 02:38 UTC, krschacht commented
All looks good, merging now., sorry for being MIA a couple days.

2024-11-16 02:38 UTC, merged