Assistants page
AllYourBot/hostedgpt pull request #559
Opened 2024-11-20 06:06 UTC by drnic

Feature flag `ASSISTANTS_PAGE_FEATURE=true` provides a simple page showing the available Assistants.

<img width="1121" alt="Screenshot 2024-11-20 at 4 04 07 pm" src="https://github.com/user-attachments/assets/7656163d-a422-4831-b00b-7f3659972cf6">

This PR also includes a default description for each default Assistant.

2024-11-21 03:06 UTC, krschacht commented
I'm curious, what's your motivation for this change? You don't like that going to the root url takes you straight to an assistant?

I'm not opposed to the change. Other people might prefer this mode. But personally, if I have a quick question and I pull up my app, I don't like the extra click before I can start typing the question. So seeing this change just made me wonder if there was an issue you were trying to solve because it might spark new thinking for me.

2024-11-21 03:38 UTC, drnic commented
I was exploring what might be possible if each assistant (or "agent" as it might be known elsewhere) had some room to breath on the page; and perhaps go further to exposing the idea that these assistants aren't just "gpt-4o" or "claude-3.5" but pre-configured system prompts (plus more perhaps one day).

The idea for the page came from seeing the magicschool.ai home page (which calls them Tools).

The PR is disabled by default; requiring the feature flag/env var.

It's ok if you don't want to merge it. It was an idea I was working on and figured I could share it publicly as a PR.

2024-11-22 06:24 UTC, buithehien1991 commented
@drnic 

I think it's incorrect: 

![image](https://github.com/user-attachments/assets/dc472ddb-548c-4e66-a8f9-df9ec3e13d5e)

2024-11-22 10:25 UTC, buithehien1991 commented
I saw a bug when click on converstation item sidebar
![image](https://github.com/user-attachments/assets/cf35dc3d-8199-41fd-a170-869e17b3c3fd)

2024-11-23 17:42 UTC, krschacht commented
> I was exploring what might be possible if each assistant (or "agent" as it might be known elsewhere) had some room to breath on the page; and perhaps go further to exposing the idea that these assistants aren't just "gpt-4o" or "claude-3.5" but pre-configured system prompts (plus more perhaps one day).
> 
> The idea for the page came from seeing the magicschool.ai home page (which calls them Tools).
> 
> The PR is disabled by default; requiring the feature flag/env var.
> 
> It's ok if you don't want to merge it. It was an idea I was working on and figured I could share it publicly as a PR.

Oh, that’s intriguing. The other cool thing about a page like this is when Teams are an entity in the system, this could also be where you see that it’s a private assistant or a team assistant. For example, maybe you’re part of a team which has created a Tech Support assistant which has a custom system prompt and has specific knowledge of how your company’s internal systems are configured and how to access those systems. This page would show a description of all that, make it clear that it’s a Team Assistant, and it also makes it clear that any conversations you have with this assistant are visible to the owner of that assistant. It’s like “this conversation is being recorded for quality assurance purposes” :)

I like this. Let’s merge it in and leave it behind a feature flag, just like you did, while we continue to develop this concept. But three things:

- [ ] take a look at that CSS question that I flagged
- [ ] buithehien might have discovered a bug
- [ ] also, wouldn’t it be better to keep `_assistant` reserved for the sidebar partial. That maintains consistency with _conversation, makes the diff of this PR smaller, and then your new partial could be something like `_assistant_tile`

2024-11-23 23:49 UTC, krschacht requested changes
Oops, I just realized I didn't submit the comment I had written:

2024-11-24 23:04 UTC, drnic commented on app/views/messages/_nav_column.html.erb
> +  class="flex flex-col"
Sorry, I think this idea was getting in my way so I dropped it and assumed I'd come back to it later. I'll investigate this.

2024-11-26 16:24 UTC, mattlindsey commented
> I like this. Let’s merge it in and leave it behind a feature flag, just like you did, while we continue to develop this concept. But three things:

- [ ] How about also instead of the feature flag, do this like 'My GPTs' on ChatGPT and put a menu item `My Assistants` next to `Settings` and `Logout`? To match the experience in ChatGPT.  Or do that later?

2024-11-26 22:33 UTC, drnic commented
@buithehien1991 I am unsure how to reproduce your bug sorry. To confirm, this bug only appeared when you switched to this PR's branch? When you switched back to `main` the bug went away?

2024-11-26 23:03 UTC, drnic commented
@krschacht I've rejiggered the sidebar so:

1. The main column scrolls independently of the sidebar, like https://tailwindcss.com/docs/installation
1. By default, the first assistant is sticky to the top, until you scroll pass all the assistants and then it too will disappear since you're now scrolling deep into old conversation history.
2. If new Assistants `ASSISTANTS_PAGE_FEATURE` feature is enabled, then the "Assistants" header is sticky as above; rather than any particular assistant.

2024-11-28 02:58 UTC, mattlindsey commented
> @buithehien1991 I am unsure how to reproduce your bug sorry. To confirm, this bug only appeared when you switched to this PR's branch? When you switched back to `main` the bug went away?

I also get that `Content missing` bug when switching to your branch, but it goes away when I switch back to main.  It's odd since I'm pretty sure I wasn't getting the bug when I tried your branch earlier.   Let me know if you want me to try anything.

2026-08-14 20:54 UTC, closed without merging